import { auth, db, onAuthStateChanged, ref, push, set, onValue } from "./firebase/client.js";
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
export function bindTempleVisits(root=document){
 const select=root.querySelector("#visit-temple"), form=root.querySelector("#visit-form"), history=root.querySelector("#visit-history"), status=root.querySelector("#visit-status"); if(!select||!form||!history||!status)return;
 let currentUser=null, temples={}; let unsubscribeHistory=()=>{};
 const unsubscribeTemples=onValue(ref(db,"temples"),snap=>{temples=snap.val()||{};select.innerHTML='<option value="">Select a temple</option>'+Object.entries(temples).map(([id,t])=>`<option value="${esc(id)}">${esc(t.name||id)}${t.city?" — "+esc(t.city):""}</option>`).join("")});
 const unsubscribeAuth=onAuthStateChanged(auth,user=>{currentUser=user;unsubscribeHistory();if(!user){status.innerHTML='Please <a href="auth.html">sign in</a> to record and view your temple visits.';form.hidden=true;history.innerHTML="";return;}form.hidden=false;status.textContent="Your visits are private to your account.";unsubscribeHistory=onValue(ref(db,`templeVisits/${user.uid}`),snap=>{const visits=Object.entries(snap.val()||{}).map(([id,v])=>({id,...v})).filter(v=>v.userId===user.uid).sort((a,b)=>(b.visitDate||"").localeCompare(a.visitDate||""));history.innerHTML=visits.length?visits.map(v=>`<li><strong>${esc(v.templeName||v.templeId)}</strong> — ${esc(v.visitDate||"")}<br><small>Recorded ${new Date(v.createdAt||Date.now()).toLocaleString()}</small></li>`).join(""):"<li>No temple visits recorded yet.</li>"})});
 const submit=async e=>{e.preventDefault();if(!currentUser){status.textContent="Please sign in first.";return}const templeId=select.value,visitDate=root.querySelector("#visit-date")?.value;if(!templeId||!visitDate)return;const id=push(ref(db,`templeVisits/${currentUser.uid}`)).key;await set(ref(db,`templeVisits/${currentUser.uid}/${id}`),{userId:currentUser.uid,templeId,templeName:temples[templeId]?.name||templeId,visitDate,createdAt:Date.now()});form.reset();status.textContent="Temple visit recorded successfully."};
 form.addEventListener("submit",submit); return ()=>{unsubscribeTemples();unsubscribeAuth();unsubscribeHistory();form.removeEventListener("submit",submit)};
}
